### PR TITLE
Update documentation for version 2.2.3

### PR DESCRIPTION
**Pull request by mathew-thomson**
Update documentation for version 2.2.3 - changed the dictionary and version

### CODE REVIEW

**Comment by mathew-thomson** [comment]
@yulric - when you get the chance can you review this and let me know where I'm messing up? Thank you!

**Comment by yulric** [comment]
The `d` in dictionary should be lower case i.e. it should be ODM_`d`ictionary_2.2.3.xlsx not ODM_`D`ictionary_2.2.3.xlsx. Let me know if you want me to change the code so that the dictionary file name is case insensisitve.

**Comment by mathew-thomson** [comment]
@yulric tried the name change fix but it still failed... Sorry for the trouble

**Comment by yulric** [comment]
@mathew-thomson Looks like the rename did not work. After googling it looks like on Macs Git does not pick up file renames if they just change the case, you have to use the [git mv](https://www.initialcommit.com/blog/git-mv) command in the terminal. I've fixed it now though so the build is working.

**Comment by mathew-thomson** [comment]
Thank @yulric - I noticed that when I made the file name change it didn't register as a merge change. So I tried to make some other small changes to maybe trigger the difference, but to no avail, sorry. Thank for making the changes, and sorry for the trouble!

**Pull request merged**
